[workspace]
name = "gatk-variant-calling"
version = "0.1.0"
description = "GATK variant calling workflow - from bash to Nextflow transformation"
channels = ["conda-forge", "bioconda"]
platforms = ["linux-64"]

[dependencies]
openjdk = "==17.0.18"
nextflow = ">=25.10.4,<26"
singularity = ">=2.4.6,<3"
nf-test = ">=0.9.4,<0.10"